import Link from "next/link";import PhoneVisual from "./PhoneVisual";import {iphone17} from "@/lib/products";
const features=[['camera','48MP','Dual Fusion camera','Detail in every frame.'],['display','120Hz','Super Retina XDR','Fluid, bright, immersive.'],['chip','A19','Next-level performance','Fast. Efficient. Effortless.'],['battery','30h','Video playback','Power that stays with you.'],['design','5','Refined finishes','A colour for every style.'],['connect','5G','Ready to connect','Speed wherever you go.']];
const specs=[['Display','6.3-inch Super Retina XDR OLED','ProMotion up to 120Hz · Always-On'],['Chip','A19 chip','Fast, efficient everyday performance'],['Camera','Dual 48MP Fusion system','18MP Center Stage front camera'],['Battery','Up to 30 hours video playback','Fast-charge capable'],['Storage','256GB or 512GB','Choose the space that fits'],['Connectivity','5G · Wi-Fi · Bluetooth','USB-C connectivity'],['Security','Face ID','Secure authentication'],['Operating system','iOS','Powerful, personal and intuitive']];
export default function LandingSections(){return <>
<section className="intro section" id="features"><div className="section-head"><span>MEET IPHONE 17</span><h2>Made to stand out.<br/><em>Built to keep up.</em></h2></div><div className="duo-stage"><PhoneVisual side="back"/><PhoneVisual/><div className="float-card fc-one"><b>6.3″</b><span>Immersive display</span></div><div className="float-card fc-two"><b>5 finishes</b><span>Made for you</span></div></div></section>
<section className="bento section"><div className="section-head compact"><span>THE HIGHLIGHTS</span><h2>Everything you need.<br/><em>Beautifully considered.</em></h2></div><div className="bento-grid">{features.map((f,i)=><article className={`bento-card card-${f[0]}`} key={f[0]}><span>0{i+1}</span><div className={`feature-art ${f[0]}`}><i/></div><strong>{f[1]}</strong><h3>{f[2]}</h3><p>{f[3]}</p></article>)}</div></section>
<section className="camera-story"><div className="camera-copy"><span>CAMERA</span><h2>Every moment.<br/><em>In its best light.</em></h2><p>A dual 48MP Fusion camera system brings remarkable detail to landscapes, portraits and everything between.</p><div className="camera-stats"><b>48MP <small>Main</small></b><b>48MP <small>Ultra Wide</small></b></div></div><div className="lens-cluster"><i/><i/><i/><div className="photo-chip">Shot on iPhone 17</div></div></section>
<section className="display-story section"><div className="display-copy"><span>SUPER RETINA XDR</span><h2>A display that<br/><em>moves with you.</em></h2><div className="badges"><b>120Hz ProMotion</b><b>Always-On</b><b>3000 nits outdoors</b></div></div><div className="screen-demo"><PhoneVisual/><div className="screen-glow"/></div></section>
<section className="performance-story section"><div className="chip-visual"><span>NOVA / SILICON</span><b>A19</b><i/></div><div><span className="overline">PERFORMANCE</span><h2>Power without<br/><em>the noise.</em></h2><p>The A19 chip keeps apps, creative work and games moving with responsive, efficient performance.</p><div className="metric-row"><b>CPU<small>Responsive</small></b><b>GPU<small>Immersive</small></b><b>Neural<small>Intelligent</small></b></div></div></section>
<section className="battery-story section"><span>BATTERY</span><h2>More day.<br/><em>Less waiting.</em></h2><div className="battery-meter"><div/><b>30<small>hours<br/>video playback</small></b></div><p>Charge to 50% in around 20 minutes with a 40W or higher adapter.</p></section>
<section className="shop-section section"><div className="shop-visual"><PhoneVisual side="back"/><span>Available in five refined finishes</span></div><div><span className="overline">MAKE IT YOURS</span><h2>Choose your<br/>iPhone 17.</h2><p>Five colours. Two storage sizes. One remarkably capable iPhone.</p><div className="shop-swatches">{iphone17.colors.map(c=><i key={c.id} style={{background:c.hex}} title={c.name}/>)}</div><p className="shop-price">From €959</p><Link href="/product/iphone-17" className="btn primary">Configure yours</Link></div></section>
<section className="specs section" id="specs"><div className="section-head compact"><span>TECHNICAL DETAILS</span><h2>All the essentials.<br/><em>At a glance.</em></h2></div><div className="spec-grid">{specs.map(s=><details key={s[0]}><summary>{s[0]}<i>+</i></summary><b>{s[1]}</b><p>{s[2]}</p></details>)}</div></section>
<section className="compare section" id="compare"><div><span>COMPARE STORAGE</span><h2>Find your fit.</h2></div><article><b>256GB</b><p>For everyday photos, apps and video.</p><strong>€959</strong></article><article><b>512GB</b><p>Extra room for creators and collectors.</p><strong>€1,209</strong></article></section>
<section className="benefits section" id="support"><div className="section-head compact"><span>THE NOVA STANDARD</span><h2>Premium service.<br/><em>From click to delivery.</em></h2></div><div className="benefit-grid">{[['↗','Fast delivery','Flexible tracked shipping across Spain.'],['◇','Official warranty','Shop with confidence and dedicated support.'],['⌁','Secure checkout','Your personal details stay protected.'],['↩','Easy returns','A clear, straightforward returns process.'],['◎','Real support','Helpful people when you need them.']].map(x=><article key={x[1]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section className="closing"><PhoneVisual/><div><span>IPHONE 17</span><h2>Ready for<br/>what’s next?</h2><p>From €959</p><Link href="/product/iphone-17" className="btn light">Buy iPhone 17</Link></div></section></>}
