/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { brandOrder, catalogProducts } from "@/lib/catalog";

const featuredSlugs = ["galaxy-s26-ultra", "iphone-17-pro-max", "vivo-x300-pro", "oppo-find-x9-pro", "xiaomi-17-ultra", "honor-x9d"];
const featured = featuredSlugs.map(slug => catalogProducts.find(product => product.slug === slug)!);

function HomeCard({ slug }: { slug: string }) {
  const product = catalogProducts.find(item => item.slug === slug)!;
  return <Link className="home-product-card" href={`/product/${product.slug}`} aria-label={`View ${product.model}`}><span className="home-product-media" style={{ background: product.images.card.background }}><img src={product.images.card.src} alt={product.images.card.alt} style={{ "--fit": product.images.card.fit, "--position": product.images.card.position ?? "center", "--mobile-fit": product.images.card.mobileFit ?? product.images.card.fit, "--mobile-position": product.images.card.mobilePosition ?? product.images.card.position ?? "center", "--scale": product.images.card.scale ?? 1 } as React.CSSProperties} /></span><span>{product.brand}</span><h3>{product.model}</h3><p>{product.description}</p><b>View details →</b></Link>;
}

export default function StoreHome() {
  return <div className="store-home"><section className="store-hero"><span>NOVA</span><h1>Premium phones from the brands that matter.</h1><p>Official photography. Manufacturer-sourced details. One considered catalog.</p><div><Link className="button primary" href="/phones">Shop phones</Link><Link className="button ghost" href="#brands">Browse brands</Link></div></section><section className="home-featured"><header><span>FEATURED PHONES</span><h2>Flagships, selected.</h2></header><div>{featured.map(product => <HomeCard slug={product.slug} key={product.slug} />)}</div></section><section className="home-brands" id="brands"><span>SHOP BY BRAND</span><h2>Nine brands.<br/>One clear view.</h2><nav>{brandOrder.map(brand => <Link href={`/phones#${brand.toLowerCase()}`} key={brand}>{brand}<b>↗</b></Link>)}</nav></section><section className="home-brand-split"><div><span>APPLE</span><h2>iPhone 17 Pro.</h2><p>A19 Pro performance and the Pro Fusion camera system in two sizes.</p><Link className="button ghost" href="/phones#apple">Explore Apple</Link></div><HomeCard slug="iphone-17-pro-max"/><div><span>SAMSUNG</span><h2>Galaxy flagships.</h2><p>Ultra capability and foldable innovation, together in the NOVA catalog.</p><Link className="button ghost" href="/phones#samsung">Explore Samsung</Link></div><HomeCard slug="galaxy-z-fold7"/></section><section className="home-others"><header><span>MORE TO EXPLORE</span><h2>Distinctive flagships.</h2></header><div><HomeCard slug="vivo-x300-pro"/><HomeCard slug="oppo-find-x9-pro"/><HomeCard slug="xiaomi-17-ultra"/><HomeCard slug="infinix-zero-40-5g"/></div></section><section className="home-benefits"><div><b>Official sources</b><span>Manufacturer information</span></div><div><b>Premium selection</b><span>Flagships across nine brands</span></div><div><b>Secure checkout</b><span>Protected purchase flow</span></div><div><b>Dedicated support</b><span>Before and after delivery</span></div></section></div>;
}
