import { iphone17ProMax } from "./products";
import { productImages, type ProductImage, type ProductImages } from "./product-images";

export const catalogAssetPath = (slug: string, file: string) => `/nova-phone-store/products/${slug}/${file}`;
export type { ProductImage, ProductImages } from "./product-images";
export type ProductHighlight = { title: string; text: string };
export type SpecGroup = { title: string; items: readonly { label: string; value: string }[] };
export type CatalogProduct = {
  slug: string; brand: string; model: string; tagline: string; description: string;
  officialProductUrl: string; image: string; cardImage: ProductImage; gallery: readonly ProductImage[];
  colors: readonly string[]; storage: readonly string[]; highlights: readonly ProductHighlight[];
  stories: { design: string; display: string; performance: string; camera: string; battery: string; software: string };
  specs: readonly SpecGroup[]; price?: number; featured?: boolean; images: ProductImages;
};
type CatalogProductData = Omit<CatalogProduct, "images">;

const image = (src: string, alt: string, options: Partial<ProductImage> = {}): ProductImage => ({ src, alt, fit: "contain", background: "#f4f4f2", ...options });
const item = (label: string, value: string) => ({ label, value });
const specs = (display: string, performance: string, memory: string, cameras: string, battery: string, connectivity: string, design: string, software: string): readonly SpecGroup[] => [
  { title: "Display", items: [item("Display", display)] }, { title: "Performance & memory", items: [item("Platform", performance), item("Memory", memory)] },
  { title: "Cameras", items: [item("Camera system", cameras)] }, { title: "Power", items: [item("Battery & charging", battery)] },
  { title: "Connectivity", items: [item("Wireless & ports", connectivity)] }, { title: "Design", items: [item("Build", design)] },
  { title: "Software", items: [item("Operating system", software)] },
];
const highlights = (display: string, chip: string, camera: string, battery: string): readonly ProductHighlight[] => [
  { title: "Display", text: display }, { title: "Performance", text: chip }, { title: "Camera", text: camera }, { title: "Power", text: battery },
];
const genericStories = (design: string, display: string, performance: string, camera: string, battery: string, software: string) => ({ design, display, performance, camera, battery, software });

const apple = iphone17ProMax.images;
const samsungS26 = "https://image-us.samsung.com/us/smartphones/galaxy-s26-ultra/images/galaxy-s26-ultra-features-kv.jpg";
const samsungFold = "https://image-us.samsung.com/us/smartphones/galaxy-z-fold7/images/galaxy-z-fold7-features-kv.jpg";
const note = "https://d3o31au25zfcly.cloudfront.net/newfileadmin/usp/note/note40proplus5g/assets/pc/sec1/kv_pc/kv_1.webp";

export const brandOrder = ["Samsung", "Apple", "Vivo", "Honor", "Tecno", "Infinix", "Oppo", "Xiaomi", "Redmi"] as const;
export const brandIntros: Record<(typeof brandOrder)[number], string> = {
  Samsung: "Galaxy innovation across flagship and foldable form factors.", Apple: "The iPhone Pro family, built around Apple silicon and Pro camera systems.", Vivo: "Imaging-led flagship smartphones from vivo.", Honor: "Distinctive smartphones designed around durability and display technology.", Tecno: "Camera-focused mobile technology from TECNO.", Infinix: "Performance and imaging devices from Infinix.", Oppo: "Find-series flagship imaging and design from OPPO.", Xiaomi: "Xiaomi flagship phones and imaging technology.", Redmi: "Performance-focused Redmi smartphones.",
};

const catalogProductData: readonly CatalogProductData[] = [
  { slug:"galaxy-s26-ultra",brand:"Samsung",model:"Galaxy S26 Ultra",tagline:"The Ultra experience, refined.",description:"Samsung's flagship Galaxy pairs a large immersive display, S Pen capability and an advanced multi-camera system.",officialProductUrl:"https://www.samsung.com/us/smartphones/galaxy-s26-ultra/",image:samsungS26,cardImage:image(samsungS26,"Galaxy S26 Ultra",{fit:"cover",position:"50% 50%",background:"#050505"}),gallery:[image(samsungS26,"Galaxy S26 Ultra hero",{fit:"cover"}),image("https://images.samsung.com/is/image/samsung/assets/us/smartphones/galaxy-s26-ultra/images/galaxy-s26-ultra-features-colors-durability-b.jpg","Galaxy S26 Ultra finishes",{fit:"cover"}),image("https://images.samsung.com/is/image/samsung/assets/us/smartphones/galaxy-s26-ultra/compare/images/galaxy-s26-ultra-share-image.jpg","Galaxy S26 Ultra design")],colors:["Cobalt Violet","Black","White","Sky Blue"],storage:["256GB","512GB","1TB"],highlights:highlights("Expansive Dynamic AMOLED 2X display.","Galaxy flagship processing with Galaxy AI.","200MP wide camera and versatile zoom system.","All-day battery design with fast charging."),stories:genericStories("A precision-built Ultra silhouette with integrated S Pen.","A bright, adaptive AMOLED canvas built for work and entertainment.","Flagship processing supports demanding creative work and on-device intelligence.","A high-resolution wide camera anchors a flexible multi-lens system.","Power management is designed around a full day of flagship use.","One UI brings Galaxy AI tools into everyday workflows."),specs:specs("Dynamic AMOLED 2X; adaptive high refresh rate","Samsung Galaxy flagship platform","256GB, 512GB or 1TB storage","200MP main camera with ultra-wide and telephoto cameras","Fast wired and wireless charging","5G, Wi‑Fi, Bluetooth, NFC and USB‑C","Armor-grade flagship construction with integrated S Pen","Android with Samsung One UI"),featured:true },
  { slug:"galaxy-z-fold7",brand:"Samsung",model:"Galaxy Z Fold7",tagline:"An Ultra experience that unfolds.",description:"A slim Galaxy foldable that opens to a tablet-sized canvas for multitasking, creativity and entertainment.",officialProductUrl:"https://www.samsung.com/us/smartphones/galaxy-z-fold7/",image:samsungFold,cardImage:image(samsungFold,"Galaxy Z Fold7 unfolded",{fit:"cover",background:"#dfe7ee"}),gallery:[image(samsungFold,"Galaxy Z Fold7 unfolded",{fit:"cover"}),image("https://image-us.samsung.com/us/smartphones/galaxy-z-fold7/images/galaxy-z-fold7-share-image.jpg","Galaxy Z Fold7 profile",{fit:"cover"}),image("https://images.samsung.com/is/image/samsung/assets/us/smartphones/galaxy-z-fold7/images/galaxy-Z-crosslinking-banner-moohan-101625.jpg","Galaxy Z Fold7 in use",{fit:"cover"})],colors:["Blue Shadow","Silver Shadow","Jet Black"],storage:["256GB","512GB","1TB"],highlights:highlights("8-inch main screen and practical cover display.","Snapdragon 8 Elite for Galaxy.","200MP wide camera.","Dual-battery system with wired and wireless charging."),stories:genericStories("A thinner, lighter foldable built around Samsung's Armor FlexHinge.","The expansive main display turns mobile work into a multi-window experience.","Flagship silicon powers productivity, gaming and Galaxy AI.","The 200MP main camera brings Ultra-grade detail to a foldable.","A dual-cell battery supports the folding form factor.","One UI includes taskbar and multi-window tools tailored to the large screen."),specs:specs("8.0-inch main Dynamic AMOLED 2X; 6.5-inch cover display; up to 120Hz","Snapdragon 8 Elite for Galaxy","256GB, 512GB or 1TB storage","200MP wide, 12MP ultra-wide and 10MP telephoto; front and under-display cameras","4400mAh typical dual battery; wired and wireless charging","5G, Wi‑Fi, Bluetooth, NFC and USB‑C","Foldable Armor FlexHinge design","Android with Samsung One UI"),featured:true },
  { slug:"iphone-17-pro-max",brand:"Apple",model:"iPhone 17 Pro Max",tagline:"Pro power. Max canvas.",description:iphone17ProMax.description,officialProductUrl:iphone17ProMax.source,image:apple.hero,cardImage:image(apple.hero,"iPhone 17 Pro Max in Cosmic Orange",{fit:"cover",background:"#1c100c"}),gallery:[image(apple.hero,"iPhone 17 Pro Max front and back",{fit:"cover"}),image(apple.finishes,"iPhone 17 Pro finish lineup",{fit:"cover"}),image(apple.camera,"iPhone 17 Pro camera system",{fit:"cover"}),image(apple.display,"iPhone 17 Pro Max display",{fit:"cover"})],colors:["Cosmic Orange","Deep Blue","Silver"],storage:["256GB","512GB","1TB","2TB"],price:1199,highlights:highlights("6.9-inch Super Retina XDR with ProMotion.","A19 Pro with Apple-designed vapor chamber.","48MP Pro Fusion camera system.","Apple's best iPhone battery life."),stories:genericStories("Heat-forged aluminium unibody with Ceramic Shield 2 front protection.","6.9-inch Super Retina XDR with Always-On, ProMotion and up to 3000 nits outdoors.","A19 Pro combines a 6-core CPU and advanced GPU with sustained thermal performance.","Three 48MP Fusion cameras cover Main, Ultra Wide and Telephoto perspectives.","Up to 39 hours of video playback, according to Apple.","iOS 26 with Apple Intelligence and Emergency SOS via satellite."),specs:specs("6.9-inch Super Retina XDR OLED; 2868×1320; 1–120Hz ProMotion; 3000 nits peak outdoor","A19 Pro; 6-core CPU; 6-core GPU; 16-core Neural Engine","256GB, 512GB, 1TB or 2TB","48MP Fusion Main, 48MP Fusion Ultra Wide and 48MP Fusion Telephoto; 18MP Center Stage front camera","Up to 39 hours video playback; MagSafe and Qi2 wireless charging","5G, Wi‑Fi 7, Bluetooth 6, NFC, Thread and USB‑C","163.4 × 78.0 × 8.75mm; 233g; aluminium unibody; IP68","iOS 26"),featured:true },
  { slug:"iphone-17-pro",brand:"Apple",model:"iPhone 17 Pro",tagline:"Pro, in the perfect size.",description:"A 6.3-inch Pro iPhone with A19 Pro, three 48MP Fusion cameras and a heat-forged aluminium unibody.",officialProductUrl:iphone17ProMax.source,image:apple.finishes,cardImage:image(apple.finishes,"iPhone 17 Pro finish lineup",{fit:"cover",position:"60% 50%",background:"#ddd8d0"}),gallery:[image(apple.finishes,"iPhone 17 Pro finishes",{fit:"cover"}),image(apple.camera,"iPhone 17 Pro camera close-up",{fit:"cover"}),image(apple.design,"iPhone 17 Pro design",{fit:"cover"}),image(apple.performance,"iPhone 17 Pro with Clear Case",{fit:"cover"})],colors:["Cosmic Orange","Deep Blue","Silver"],storage:["256GB","512GB","1TB"],highlights:highlights("6.3-inch Super Retina XDR with ProMotion.","A19 Pro with vapor chamber cooling.","Three 48MP Fusion cameras.","Up to 33 hours video playback."),stories:genericStories("A compact Pro form built from a heat-forged aluminium unibody.","Super Retina XDR combines Always-On technology, ProMotion and excellent outdoor visibility.","A19 Pro provides sustained performance for demanding games and creative tools.","Main, Ultra Wide and Telephoto cameras are all built around 48MP Fusion sensors.","Apple rates iPhone 17 Pro for up to 33 hours of video playback.","iOS 26 with Apple Intelligence and satellite safety features."),specs:specs("6.3-inch Super Retina XDR OLED; 2622×1206; 1–120Hz ProMotion; 3000 nits peak outdoor","A19 Pro; 6-core CPU; 6-core GPU; 16-core Neural Engine","256GB, 512GB or 1TB","48MP Fusion Main, Ultra Wide and Telephoto; 18MP Center Stage front camera","Up to 33 hours video playback; MagSafe and Qi2","5G, Wi‑Fi 7, Bluetooth 6, NFC, Thread and USB‑C","150.0 × 71.9 × 8.75mm; 206g; aluminium unibody; IP68","iOS 26"),featured:true },
  { slug:"vivo-x300-pro",brand:"Vivo",model:"vivo X300 Pro",tagline:"ZEISS imaging, pushed further.",description:"A photography-led flagship built around ZEISS optics, a 200MP telephoto camera and flagship MediaTek performance.",officialProductUrl:"https://www.vivo.com/en/products/x300-pro",image:"https://asia-exstatic-vivofs.vivo.com/PSee2l50xoirPK7y/product/1770276743814/zip/img/pc/vivo-x300-pro.png.webp",cardImage:image("https://asia-exstatic-vivofs.vivo.com/PSee2l50xoirPK7y/product/1770276743814/zip/img/pc/vivo-x300-pro.png.webp","vivo X300 Pro",{background:"#e7e4dc",scale:1.08}),gallery:[image("https://asia-exstatic-vivofs.vivo.com/PSee2l50xoirPK7y/product/1770276743814/zip/img/pc/vivo-x300-pro.png.webp","vivo X300 Pro"),image("https://asia-exstatic-vivofs.vivo.com/PSee2l50xoirPK7y/product/1770276743814/zip/img/wap/os.png","vivo X300 Pro software experience",{fit:"cover"})],colors:["Dune Brown","Phantom Black"],storage:["512GB"],highlights:highlights("6.78-inch 120Hz AMOLED.","MediaTek Dimensity 9500.","200MP ZEISS APO telephoto.","6510mAh battery with 90W charging."),stories:genericStories("A balanced flagship body built around a prominent ZEISS camera ring.","A high-refresh AMOLED display keeps interaction fluid.","Dimensity 9500 drives imaging, gaming and on-device AI.","The ZEISS APO telephoto camera is designed for long-range detail.","A high-capacity silicon battery supports 90W wired and wireless charging.","OriginOS delivers vivo's connected flagship experience."),specs:specs("6.78-inch AMOLED; 120Hz","MediaTek Dimensity 9500","512GB storage","50MP main, 50MP ultra-wide and 200MP ZEISS APO telephoto; 50MP front","6510mAh; 90W wired and 40W wireless charging","5G, Wi‑Fi, Bluetooth, NFC and USB‑C","IP68/IP69 water and dust resistance","OriginOS"),featured:true },
  { slug:"honor-x9d",brand:"Honor",model:"HONOR X9d",tagline:"Built for the unexpected.",description:"A durability-focused HONOR phone with a high-capacity battery, bright AMOLED display and high-resolution main camera.",officialProductUrl:"https://www.honor.com/global/phones/honor-x9d/",image:"https://www.honor.com/content/dam/honor/common/product-list/product-series/honor-x9d/honor-x9d-red-list.png",cardImage:image("https://www.honor.com/content/dam/honor/common/product-list/product-series/honor-x9d/honor-x9d-red-list.png","HONOR X9d",{background:"#eee9e6",scale:1.12}),gallery:[image("https://www.honor.com/content/dam/honor/common/product-list/product-series/honor-x9d/honor-x9d-red-list.png","HONOR X9d in red")],colors:["Reddish Brown","Forest Green","Midnight Black"],storage:["256GB","512GB"],highlights:highlights("6.79-inch 120Hz AMOLED.","Snapdragon 6 Gen 4.","108MP main camera with OIS.","8300mAh silicon-carbon battery."),stories:genericStories("Designed for enhanced resistance to drops, water and dust.","A bright, high-refresh AMOLED panel offers a spacious view.","Snapdragon 6 Gen 4 balances efficiency with responsive everyday performance.","The 108MP main camera includes optical image stabilisation.","The 8300mAh silicon-carbon battery prioritises endurance.","MagicOS adds HONOR productivity and device-connectivity features."),specs:specs("6.79-inch AMOLED; 120Hz","Snapdragon 6 Gen 4","256GB or 512GB storage","108MP main with OIS; 5MP ultra-wide; 16MP front","8300mAh; 66W wired charging","5G, Wi‑Fi, Bluetooth, NFC and USB‑C","IP69K-rated water and dust resistance","Android with MagicOS"),featured:true },
  { slug:"tecno-camon-40-premier-5g",brand:"Tecno",model:"TECNO CAMON 40 Premier 5G",tagline:"Imaging in every light.",description:"TECNO's camera-focused flagship combines three 50MP rear cameras with a fast AMOLED display and Dimensity performance.",officialProductUrl:"https://www.tecno-mobile.com/phones/product-detail/product/camon-40-premier-5g/",image:"https://d13pvy8xd75yde.cloudfront.net/global/phones/camon40/camon-40-premier-5g/assets/images-perf-game-cm8-white-1.png",cardImage:image("https://d13pvy8xd75yde.cloudfront.net/global/phones/camon40/camon-40-premier-5g/assets/images-perf-game-cm8-white-1.png","TECNO CAMON 40 Premier 5G",{background:"#dedbd5",scale:1.16}),gallery:[image("https://d13pvy8xd75yde.cloudfront.net/global/phones/camon40/camon-40-premier-5g/assets/images-perf-game-cm8-white-1.png","CAMON 40 Premier 5G")],colors:["Emerald Lake Green","Galaxy Black"],storage:["256GB"],highlights:highlights("6.67-inch 144Hz AMOLED.","Dimensity 8350 Ultimate.","Triple 50MP rear camera system.","5100mAh battery and 70W charging."),stories:genericStories("A slim, IP-rated body with a distinctive camera island.","The 144Hz AMOLED display is tuned for smooth motion.","Dimensity 8350 Ultimate supports gaming and computational photography.","Main, ultra-wide and periscope telephoto cameras each use 50MP sensors.","70W charging replenishes the 5100mAh battery.","HiOS includes TECNO AI features and cross-device tools."),specs:specs("6.67-inch 1.5K AMOLED; 144Hz","MediaTek Dimensity 8350 Ultimate","12GB RAM; 256GB storage","50MP main with OIS, 50MP ultra-wide, 50MP 3x periscope; 50MP front","5100mAh; 70W wired charging","5G, Wi‑Fi, Bluetooth, NFC and USB‑C","IP68/IP69 water and dust resistance","Android with HiOS") },
  { slug:"infinix-note-40-pro-plus-5g",brand:"Infinix",model:"Infinix NOTE 40 Pro+ 5G",tagline:"All-round fast charge.",description:"A curved-display NOTE phone centered on Infinix All-Round FastCharge 2.0 and a 108MP OIS camera.",officialProductUrl:"https://www.infinixmobility.com/NOTE-40-Pro+-5G",image:note,cardImage:image(note,"Infinix NOTE 40 Pro+ 5G",{fit:"cover",background:"#191719"}),gallery:[image(note,"NOTE 40 Pro+ 5G hero",{fit:"cover"}),image("https://d3o31au25zfcly.cloudfront.net/newfileadmin/usp/note/note40proplus5g/assets/pc/sec2/img-phone-charge.webp","NOTE 40 Pro+ 5G charging"),image("https://d3o31au25zfcly.cloudfront.net/newfileadmin/usp/note/note40proplus5g/assets/mb/sec2/img-camera.webp","NOTE 40 Pro+ camera")],colors:["Obsidian Black","Vintage Green"],storage:["256GB"],highlights:highlights("6.78-inch 120Hz curved AMOLED.","Dimensity 7020 5G.","108MP OIS main camera.","100W wired and 20W wireless charging."),stories:genericStories("A curved display meets a textured rear finish.","The 120Hz AMOLED panel is protected by Corning Gorilla Glass.","Dimensity 7020 supplies efficient 5G performance.","A 108MP main camera uses OIS for steadier captures.","All-Round FastCharge 2.0 supports wired, wireless and reverse charging modes.","XOS adds Infinix productivity and personalisation features."),specs:specs("6.78-inch FHD+ curved AMOLED; 120Hz","MediaTek Dimensity 7020","12GB RAM; 256GB storage","108MP main with OIS; 32MP front","4600mAh; 100W wired and 20W wireless MagCharge","5G, Wi‑Fi, Bluetooth, NFC and USB‑C","IP53 splash resistance","Android with XOS") },
  { slug:"infinix-zero-40-5g",brand:"Infinix",model:"Infinix ZERO 40 5G",tagline:"Created for creators.",description:"A creator-led 5G phone with 4K front-and-rear video, a 144Hz AMOLED display and an ultra-wide 50MP front camera.",officialProductUrl:"https://www.infinixmobility.com/ZERO-40-5G",image:"https://d3o31au25zfcly.cloudfront.net/newfileadmin/usp/zero/zero-40-5g/section-1/mb/new-kv-mb-v2.webp",cardImage:image("https://d3o31au25zfcly.cloudfront.net/newfileadmin/usp/zero/zero-40-5g/section-1/mb/new-kv-mb-v2.webp","Infinix ZERO 40 5G",{fit:"cover",background:"#bea89d"}),gallery:[image("https://d3o31au25zfcly.cloudfront.net/newfileadmin/usp/zero/zero-40-5g/section-1/mb/new-kv-mb-v2.webp","ZERO 40 5G",{fit:"cover"})],colors:["Violet Garden","Moving Titanium","Rock Black"],storage:["256GB","512GB"],highlights:highlights("6.78-inch 144Hz curved AMOLED.","Dimensity 8200 Ultimate.","108MP OIS main and 50MP ultra-wide front cameras.","5000mAh battery with wired and wireless charging."),stories:genericStories("A slim curved body frames the circular camera system.","A 144Hz AMOLED display makes motion feel immediate.","Dimensity 8200 Ultimate supports 5G creation and gaming.","Front and rear cameras support 4K 60fps video for creator workflows.","The 5000mAh battery supports wired and wireless charging.","XOS includes GoPro connectivity and editing tools."),specs:specs("6.78-inch curved AMOLED; 144Hz","MediaTek Dimensity 8200 Ultimate","12GB RAM; 256GB or 512GB storage","108MP OIS main, 50MP ultra-wide; 50MP ultra-wide front","5000mAh; 45W wired and 20W wireless charging","5G, Wi‑Fi 6E, Bluetooth, NFC and USB‑C","IP54 dust and splash resistance","Android with XOS") },
  { slug:"infinix-gt-20-pro",brand:"Infinix",model:"Infinix GT 20 Pro",tagline:"Built to play.",description:"A gaming-focused GT phone with a dedicated display chip, high-refresh AMOLED panel and Dimensity 8200 Ultimate.",officialProductUrl:"https://www.infinixmobility.com/gt-20-pro",image:"https://d3o31au25zfcly.cloudfront.net/newfileadmin/usp/gt/gt20pro_v7/id/images/kv-pc.webp",cardImage:image("https://d3o31au25zfcly.cloudfront.net/newfileadmin/usp/gt/gt20pro_v7/id/images/kv-pc.webp","Infinix GT 20 Pro",{fit:"cover",background:"#080915"}),gallery:[image("https://d3o31au25zfcly.cloudfront.net/newfileadmin/usp/gt/gt20pro_v7/id/images/kv-pc.webp","GT 20 Pro gaming design",{fit:"cover"})],colors:["Mecha Blue","Mecha Orange","Mecha Silver"],storage:["256GB"],highlights:highlights("6.78-inch 144Hz AMOLED.","Dimensity 8200 Ultimate plus Pixelworks X5 Turbo.","108MP OIS main camera.","5000mAh battery with 45W charging."),stories:genericStories("Cyber Mecha lighting gives GT a recognisable gaming identity.","The 144Hz AMOLED works with a dedicated display chip for fluid play.","Dimensity 8200 Ultimate and the Esports Stable Frame-rate Engine target sustained gaming.","A 108MP OIS camera handles everyday imaging.","Bypass charging helps manage heat while plugged in during play.","XOS for GT includes game-focused controls."),specs:specs("6.78-inch FHD+ AMOLED; 144Hz","MediaTek Dimensity 8200 Ultimate; Pixelworks X5 Turbo display chip","12GB RAM; 256GB storage","108MP main with OIS; 32MP front","5000mAh; 45W wired charging; bypass charging","5G, Wi‑Fi, Bluetooth, NFC and USB‑C","Mecha Loop LED design; IP54","Android with XOS for GT") },
  { slug:"oppo-find-x9-pro",brand:"Oppo",model:"OPPO Find X9 Pro",tagline:"A master of light and distance.",description:"OPPO's Hasselblad flagship combines a 200MP telephoto camera, flagship MediaTek performance and a high-capacity battery.",officialProductUrl:"https://www.oppo.com/en/smartphones/series-find-x/find-x9-pro/",image:"https://www.oppo.com/content/dam/oppo/common/mkt/v2-2/find-x9-series-en/listpage/find-x9-pro/480-600-white-v2.png",cardImage:image("https://www.oppo.com/content/dam/oppo/common/mkt/v2-2/find-x9-series-en/listpage/find-x9-pro/480-600-white-v2.png","OPPO Find X9 Pro",{background:"#e8e8e6",scale:1.12}),gallery:[image("https://www.oppo.com/content/dam/oppo/common/mkt/v2-2/find-x9-series-en/listpage/find-x9-pro/480-600-white-v2.png","OPPO Find X9 Pro")],colors:["Silk White","Titanium Charcoal"],storage:["512GB"],highlights:highlights("6.78-inch 120Hz ProXDR display.","MediaTek Dimensity 9500.","200MP Hasselblad telephoto camera.","7500mAh battery and 80W SUPERVOOC."),stories:genericStories("A refined flat-sided body balances the Hasselblad camera system.","The 120Hz ProXDR panel is tuned for bright, accurate viewing.","Dimensity 9500 drives ColorOS and computational imaging.","The 200MP telephoto camera extends detail at long focal lengths.","A 7500mAh silicon-carbon battery supports wired and wireless charging.","ColorOS integrates productivity, sharing and AI tools."),specs:specs("6.78-inch AMOLED ProXDR; 120Hz","MediaTek Dimensity 9500","16GB RAM; 512GB storage","50MP main, 50MP ultra-wide and 200MP Hasselblad telephoto; 50MP front","7500mAh; 80W SUPERVOOC and 50W AIRVOOC","5G, Wi‑Fi, Bluetooth, NFC and USB‑C","IP68/IP69 water and dust resistance","ColorOS") },
  { slug:"oppo-find-x8-ultra",brand:"Oppo",model:"OPPO Find X8 Ultra",tagline:"Ultra detail, from every camera.",description:"A Hasselblad imaging flagship with four 50MP rear cameras, dual periscope zoom and Snapdragon performance.",officialProductUrl:"https://www.oppo.com/cn/smartphones/series-find-x/find-x8-ultra/",image:"https://www.oppo.com/content/dam/oppo_com/common/mkt/v2-2/cn-find-x8-series/find-x8-ultra/listpage/427-600-pink.png",cardImage:image("https://www.oppo.com/content/dam/oppo_com/common/mkt/v2-2/cn-find-x8-series/find-x8-ultra/listpage/427-600-pink.png","OPPO Find X8 Ultra",{background:"#eee8e7",scale:1.1}),gallery:[image("https://www.oppo.com/content/dam/oppo_com/common/mkt/v2-2/cn-find-x8-series/find-x8-ultra/listpage/427-600-pink.png","OPPO Find X8 Ultra")],colors:["Moonlight White","Morning Light","Starry Black"],storage:["256GB","512GB","1TB"],highlights:highlights("6.82-inch 120Hz AMOLED.","Snapdragon 8 Elite.","Quad 50MP Hasselblad camera system.","6100mAh battery with 100W charging."),stories:genericStories("A flat flagship frame surrounds a centered Hasselblad camera ring.","The 2K-class AMOLED panel supports adaptive high refresh.","Snapdragon 8 Elite enables flagship imaging and responsiveness.","Main, ultra-wide and two periscope cameras provide four distinct focal ranges.","The 6100mAh battery supports wired and wireless flash charging.","ColorOS provides OPPO's latest imaging and productivity experience."),specs:specs("6.82-inch AMOLED; QHD+; 120Hz","Snapdragon 8 Elite","12GB or 16GB RAM; 256GB, 512GB or 1TB storage","Four 50MP Hasselblad rear cameras including 3x and 6x periscopes; 32MP front","6100mAh; 100W wired and 50W wireless charging","5G, Wi‑Fi 7, Bluetooth, NFC and USB‑C","IP68/IP69 water and dust resistance","ColorOS") },
  { slug:"xiaomi-17-ultra",brand:"Xiaomi",model:"Xiaomi 17 Ultra",tagline:"The Leica flagship.",description:"Xiaomi's Ultra imaging phone is built around Leica optics, a large-format main camera and advanced telephoto photography.",officialProductUrl:"https://www.mi.com/prod/xiaomi-17-ultra",image:"https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/3f5c0cd26cf1cd44b020005fe94f8dbf.png",cardImage:image("https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/3f5c0cd26cf1cd44b020005fe94f8dbf.png","Xiaomi 17 Ultra",{background:"#e9e8e4",scale:1.12}),gallery:[image("https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/3f5c0cd26cf1cd44b020005fe94f8dbf.png","Xiaomi 17 Ultra"),image("https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/8baabd4fc4255a2cf81636335b4cf0c1.png","Xiaomi flagship detail",{fit:"cover"})],colors:["Black","White"],storage:["512GB","1TB"],highlights:highlights("Flagship adaptive-refresh AMOLED.","Snapdragon flagship platform.","Leica professional optical camera system.","High-capacity silicon-carbon battery."),stories:genericStories("An Ultra silhouette centered on the Leica camera system.","The high-resolution AMOLED display adapts smoothly to content.","Qualcomm flagship processing powers imaging and demanding apps.","Leica optics and Xiaomi computational photography prioritize natural detail.","A high-density battery supports fast wired and wireless charging.","Xiaomi HyperOS connects the phone with Xiaomi's wider ecosystem."),specs:specs("High-resolution AMOLED with adaptive high refresh rate","Qualcomm Snapdragon flagship platform","512GB or 1TB storage","Leica professional optical camera system","Fast wired and wireless charging","5G, Wi‑Fi, Bluetooth, NFC and USB‑C","Premium Ultra-series construction","Xiaomi HyperOS") },
  { slug:"xiaomi-17-pro-max",brand:"Xiaomi",model:"Xiaomi 17 Pro Max",tagline:"A larger view of Pro.",description:"A large-screen Xiaomi flagship that combines Leica imaging, flagship Snapdragon performance and a secondary rear display.",officialProductUrl:"https://www.mi.com/prod/xiaomi-17-pro-max",image:"https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/bb9e4a367f854221b60bb7b3b05e0173.png",cardImage:image("https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/bb9e4a367f854221b60bb7b3b05e0173.png","Xiaomi 17 Pro Max",{background:"#e8e5df",scale:1.12}),gallery:[image("https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/bb9e4a367f854221b60bb7b3b05e0173.png","Xiaomi 17 Pro Max"),image("https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/5f56e61ddfba022886999937ff48e7fa.png","Xiaomi 17 Pro Max design",{fit:"cover"})],colors:["Black","White","Green","Purple"],storage:["256GB","512GB","1TB"],highlights:highlights("Large high-resolution AMOLED display.","Snapdragon flagship performance.","Leica camera system and rear secondary screen.","High-capacity battery with fast charging."),stories:genericStories("A large-format Pro body integrates a useful display beside the rear cameras.","The main AMOLED panel combines high resolution with adaptive refresh.","Snapdragon flagship silicon supports gaming, imaging and local AI.","Leica-tuned cameras cover everyday and telephoto perspectives.","High-density battery technology supports the Max form factor.","Xiaomi HyperOS links main and rear display experiences."),specs:specs("Large high-resolution AMOLED with adaptive high refresh rate","Qualcomm Snapdragon flagship platform","256GB, 512GB or 1TB storage","Leica camera system with rear secondary display","Fast wired and wireless charging","5G, Wi‑Fi, Bluetooth, NFC and USB‑C","Premium construction with rear secondary screen","Xiaomi HyperOS") },
  { slug:"redmi-k80-pro",brand:"Redmi",model:"Redmi K80 Pro",tagline:"Performance, without compromise.",description:"A performance-focused Redmi flagship with Snapdragon 8 Elite, a sharp 2K display and rapid wired charging.",officialProductUrl:"https://www.mi.com/prod/redmi-k80-pro",image:"https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/c06730d1d2b34f09a7ee31c9b7559650.png",cardImage:image("https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/c06730d1d2b34f09a7ee31c9b7559650.png","Redmi K80 Pro",{background:"#eae8e2",scale:1.12}),gallery:[image("https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/c06730d1d2b34f09a7ee31c9b7559650.png","Redmi K80 Pro"),image("https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/86eb53bd70dbe20d9d4e8ec187a92dcc.png","Redmi flagship detail",{fit:"cover"})],colors:["Black","White","Blue","Green"],storage:["256GB","512GB","1TB"],highlights:highlights("6.67-inch 2K 120Hz OLED.","Snapdragon 8 Elite.","50MP OIS main camera.","6000mAh battery with 120W charging."),stories:genericStories("A clean metal-frame design puts performance first.","The 2K OLED combines sharp detail with a 120Hz refresh rate.","Snapdragon 8 Elite and a large cooling system target sustained speed.","The 50MP main camera adds optical image stabilisation.","A 6000mAh battery supports 120W wired and 50W wireless charging.","Xiaomi HyperOS includes performance and ecosystem tools."),specs:specs("6.67-inch 2K OLED; 120Hz","Snapdragon 8 Elite","12GB or 16GB RAM; 256GB, 512GB or 1TB storage","50MP main with OIS, 32MP telephoto and 8MP ultra-wide; 20MP front","6000mAh; 120W wired and 50W wireless charging","5G, Wi‑Fi 7, Bluetooth, NFC and USB‑C","Metal frame; IP68 water and dust resistance","Xiaomi HyperOS") },
];

export const catalogProducts: readonly CatalogProduct[] = catalogProductData.map(product => ({ ...product, images: productImages[product.slug] }));

export const productsByBrand = brandOrder.map(brand => ({ brand, intro: brandIntros[brand], products: catalogProducts.filter(product => product.brand === brand) }));
export const getCatalogProduct = (slug: string) => catalogProducts.find(product => product.slug === slug);
